### ISSUE TITLE
Possible problem with samsung SSDs that might be affecting razer's notebooks 

### ISSUE THREAD

**Issue by lucaszanella** [rolandguelle/razer-blade-stealth-linux#10] opened 2018-01-21 23:57 UTC
I've had corruption problems and downraded to ubuntu 16.04 which worked well until I applied some updates. It looks like there's a bug in samsung SSDs that starts with ubuntu 17.04 tat might be the cause of this, as I figured out and posted here:

https://askubuntu.com/questions/998471/razer-blade-stealth-disk-corruption-fsck-needed-probably-samsung-ssd-bug-afte

(probable fix also linked in my post)

Probably a good thing to list in this repository.

**Comment by rolandguelle** [comment] 2018-01-28 09:56
I don't have this problem, but sounds interesting & useful.

What I don't understand, what fix this issue?

The kernel parameter:
* nvme_core.default_ps_max_latency_us=5500

or updating the firmware?

* https://askubuntu.com/questions/998471/razer-blade-stealth-disk-corruption-fsck-needed-probably-samsung-ssd-bug-afte?answertab=active#tab-top
* 3.20180108.0+really20170707ubuntu17.10.1

**Comment by lucaszanella** [comment] 2018-01-28 12:12
now I don't know. I thought it was a problem with the SSD power that was fixable with latency parameters, but now they're saying it is a problem with the firmware

-------- Original Message --------

**Comment by rolandguelle** [comment] 2018-01-30 18:39
OK, I keep this issue open. Maybe we find more infos in the future.

**Comment by rolandguelle** [comment] 2018-05-07 16:54
I had problems with installing a fresh 18.10 on my machine, where I first guess I run into the same issue. But using this kernel parameters make it worse. Start the installation mode direct in Grub solves the problem.

**Comment by samr28** [comment] 2018-06-17 14:33
I had a few problems similar to this when I was running KDE neon 5.12 (ubuntu 16.04). In my case, I would often have the system go into read only mode and I would get an error every time that I opened a file or program. Then I would reboot the system and `fsck` would fix it. This didn't happen too often but it did happen quite a few times.

Then later I had a much more serious issue where the system went into read only mode but then when I booted back up, I couldn't get into `fsck` or neon. I did some tests and tried to fix it with the help of the people on the ubuntu irc but had no success. I ended up just reinstalling but instead, going with kubuntu which is based on 18.04. Since then I have had one `fsck` read only mode issue. So I'm hoping that it was something solved with ubuntu related to the m.2 ssds. I remember that one of the people on the ubuntu irc said that there was a bug that seemed to be similar to what I experienced and the bug was fixed after 16.04 (not sure when). So hopefully I don't have any of these problems with 18.04.

Razer blade stealth late 2017 512GB ssd.

**Comment by jheise** [comment] 2018-08-06 02:13
I've been running into this issue since upgrading to ubuntu 18.04, i'm fairly certain i saw it sporadically on 16.10, 17.04, and 17.10, maybe 6 to 10 times total for all of those. Since the 18.04 upgrade its been much more frequent, easily once every two weeks, often more. I'm running on a fresh install of 18.04, no kernel changes or firmware upgrades to ssd.

**Comment by samr28** [comment] 2018-08-06 03:02
@lucaszanella Yeah I actually have been having the same problems and I totally forgot about this thread. I tried the microcode updates but that didn't seem to solve the problem for me. Also I'm on 18.04 now and the issue seems to be occurring more often as @jheise said.

**Comment by lucaszanella** [comment] 2018-08-06 03:07
@jheise I applied this patch https://launchpadlibrarian.net/374634454/0001-ASPM-quirk-for-SM-PM-EVO-961.patch to the 4.15.0-23-generic ubuntu kernel (bionic) and added the following kernel parameter: nvme-core.default_ps_max_latency_us=1500

I've been using the notebook with this patch for more than one month and only had the problem in the two situations I listed. You can use the notebook for almost anything with this patch with very few or no  problems at all

**Comment by jheise** [comment] 2018-08-06 05:49
@lucaszanella Awesome! Starting to read through the backlog.

**Comment by samr28** [comment] 2018-08-06 07:11
I installed the kernel linked in this comment: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1746340/comments/134. I'll let you guys know if I run into the issue again or if it solves it.

**Comment by jheise** [comment] 2018-08-07 14:34
Prior to patching, has anyone had an issue where the hard drive doesnt show up in the bios? One a few occasions i've had to reboot several time until drive shows up again.

**Comment by jheise** [comment] 2018-08-08 02:33
Running  kernel `Linux alita 4.18.0-3-generic #4 SMP Wed Aug 1 00:12:23 CST 2018 x86_64 x86_64 x86_64 GNU/Linux` I've seen crashes twice after suspend

**Comment by lucaszanella** [comment] 2018-08-09 00:04
Did you add the kernel parameter too? In my comments you can see that im using 1500. Unfortunately I'm not at my computer right now but you should find it easily. 

I'm supposing you're using the ASPM patched kernel. There are multiple ones we tested.

**Comment by jheise** [comment] 2018-08-09 00:25
So in /etc/default/grub I have the following
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash button.lid_init_state=open nvme-core.default_ps_max_latency_us=15
00"`

but checking /proc/cmdline i see this
`BOOT_IMAGE=/boot/vmlinuz-4.18.0-3-generic root=UUID=5d60876c-02ce-4657-8a2f-31bc42f32cbd ro quiet splash button.lid_init_state=open vt.handoff=1`

**Comment by lucaszanella** [comment] 2018-08-11 02:36
Just to be sure, did you install this one: https://people.canonical.com/~khfeng/pm961-disable-aspm/? This is the one that worked for me (but I did not install this, I compiled my own with the patch that generated this). And this is the parameter: nvme-core.default_ps_max_latency_us=1500

My computer has been working for more than 30 days without problems

**Comment by jheise** [comment] 2018-08-16 04:46
I installed https://people.canonical.com/~khfeng/quirk-no-commclk/ no change in performance. Afterwards i installed the latest 4.18.0-3 kernel, that had an uptime of a day and then froze after resume. I then had to reboot twice because my drive was not showing up. At this point i'm contemplating replacing the drive.

**Comment by samr28** [comment] 2018-09-24 20:30
It sounds like this has kernel has fixed the issue. How do we go about getting it merged into the official kernel?

**Comment by lucaszanella** [comment] 2018-09-24 22:37
It's not a complete solution. It didn't work 100% for me. It gives the error after some weeks of usage or if I try to update the system

-------- Mensagem Original --------
Ativo 24 de set de 2018 17:30, Sam Roquitte escreveu:

**Comment by samr28** [comment] 2018-09-24 22:40
My system has been stable for about a month now but I haven't been updating packages. Is it possible that you accidentally updated the kernel when updating the system?

**Comment by lucaszanella** [comment] 2018-09-24 22:42
I verified and the kernel didn't update. I suggest you try to update your ubuntu. It always fails, for me, on the generating initramfs, or something like that, but the system keeps working and you can regenerate initramfs later. And also my virtual machines still give the error every 2 or 3 days.

-------- Mensagem Original --------
Ativo 24 de set de 2018 19:40, Sam Roquitte escreveu:

**Comment by samr28** [comment] 2018-10-02 19:43
I've been running 4.18.0-3-generic for the past week and so far I haven't run into any issues with the SSD. The only weird thing that I run into is that when it boots into ubuntu, the xserver doesn't start. So I just have to switch terminals and run `xstart`.

Also I'm getting really terrible battery life not (less than 3 hours) for some reason. https://github.com/rolandguelle/razer-blade-stealth-linux/issues/29

**Comment by rolandguelle** [comment] 2018-10-02 20:04
Have you tried booting Live Ubuntu 18.04 from USB with the xserver problem?
Ubuntu switched back from Wayland to X with 18.04, maybe some of your start scripts or gdm, lightdm are broken.

**Comment by rolandguelle** [comment] 2018-10-02 20:16
@samr28 solves 4.18.0-3 the SSD problem without any other tweaks / workarounds?
Could we close the issue with the (upcoming) Ubuntu 18.10?

**Comment by samr28** [comment] 2018-10-02 21:55
@rolandguelle I've been running fine on the 4.18.0-3 kernel so far but I wouldn't conclude that its fixed. I haven't tried the "download a bunch of emails" (to write a bunch of things to the drive) test. I've also been restarting every week or so which in the past seemed to prolong the self destruct timer.

I'll try the live boot tonight and see if the xserver starts up properly.

**Comment by lucaszanella** [comment] 2018-10-02 22:04
I think the issue should still be left open. I'll try the new ubuntu releases soon when I get the chance to. However, I'm still experiencing problems with the current patched kernel, and these are the patches that go to these new kernels. It's way more stable though

**Comment by rolandguelle** [comment] 2018-10-21 16:01
If this issue still exists in Ubuntu 18.10, please reopen this issue.

**Closed by rolandguelle** 2018-10-21 16:01 UTC

**Comment by lucaszanella** [comment] 2019-04-19 19:23
Just tested on ubuntu 19 which was lunched today. Couldn't even install because it had a problem in disk while installing

**Comment by sabiou** [comment] 2019-05-19 02:49
I'm actually facing this issues since two weeks.. I'm running Ubuntu 18.10 on a Lenovo Thinkpad T570

**Comment by lucaszanella** [comment] 2019-05-19 06:03
Can you enter into
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1746340 and comment that you also have this bug? There are people working on solving it in the ubuntu kernel

-------- Mensagem Original --------
Ativo 18 de mai de 2019 23:49, Farouk escreveu:

**Comment by sabiou** [comment] 2019-05-19 22:19
Okay @lucaszanella thanks I will do it asap

**Comment by lucaszanella** [comment] 2019-05-19 22:26
Meanwhile, you can try to install the kernel patch listed in this discussion by me, or in the launchpad thread. It made the error happen every 3 days instead of every hour. However, the patch is specific for Razer Blade Stealth, maybe you can ask them to make it available to Lenovo, or just wait for a general fix for all models. Anyways, reporting that you also have the bug is important for ubuntu team to fix it

-------- Mensagem Original --------
Ativo 19 de mai de 2019 19:19, Farouk escreveu:

**Comment by lucaszanella** [comment] 2019-10-03 23:09
Hi @sabiou, @samr28, @jheise

How have been your ubuntus working? Any news?

I'm having this problem a LOT and it's annoying me a lot. I can't use the computer anymore. On windows no problems happen at all!

**Comment by jheise** [comment] 2019-10-04 00:21
I ended up replacing the drive, since then I've had very few issues with it

**Comment by lucaszanella** [comment] 2019-10-04 00:23
Did you replace by another one of the same brand or a new brand? I made the mistake of buying another one of the same brand and a similar model and the problem persisted

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 3 de out de 2019 21:21, Jon Heise escreveu:

> I ended up replacing the drive, since then I've had very few issues with it
>

**Comment by lucaszanella** [comment] 2019-10-11 07:44
Hi, I didn't find the root of the problem, **BUT**...

Using Qubes OS I was able to run for more than 7 days without any problems! It normally would occur in the first hour of usage.

I guess Qubes's Xen drivers proxy the pcie requests and therefore the failing NVME/PCIE drivers aren't used. So it at least shines a light in the problem.

Maybe someone with better understanding of how Xen works can reason about which drivers are being used and which are not and discover the root of the problem!

**Comment by lattice0** [comment] 2021-06-22 18:56
I just want to say that after 2 years I remembered I had an SSD with different brand tham Samsung, a Kingston one. I installed it on my razer and it worked perfectly for days, I did several SSD stress tests and no errors. 

The error is defintely with Samsung AND linux. And it's not a faulty SSD because it happens on both of my samsung SSDs. It does not happen on Windows, neither Qubes, with any SSD.

I tested the latest Ubuntu 21.04 and the problem still happens on Samsung SSDs right on the installation screen.

Anyways I'm not even using this computer anymore, I bought a Dell XPS 13, but the error persists and it's either Samsung's or Linux fault. Probably Samsung since other brands work ok with Samsung.

**Comment by jheise** [comment] 2021-06-22 21:11
Might have been a specific batch of the Samsung drives, I replaced mine
with another Samsung and it's been working without issue ever since then.

**Comment by lattice0** [comment] 2021-06-22 21:13
The problem is that my razer is from USA and I bought the SSD in Brazil a year after but who knows...

It does not look like a hardware problem because it works perfectly with windows

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 22 de jun. de 2021 18:11, Jon Heise escreveu:
