### ISSUE TITLE
Flickering screen issue with Ubuntu 17.10

### ISSUE THREAD

**Issue by ahmadnassri** [rolandguelle/razer-blade-stealth-linux#7] opened 2017-11-13 19:59 UTC
(not sure if this is a good place to post this, but assuming this repo gets high visibility from fellow blade owners)

I've recently noticed screen flickering after ~upgrading~ switching to 17.10 (fresh install, vanilla, wayland) anybody else experiencing this?

**Comment by lucaszanella** [comment] 2017-11-13 20:03
I didn't upgrade, I installed a fresh 17.10 anf used for one week and there was no flickering at all. Now I'm im 17.04 for other reasons but I'm going to go back to 17.10 in a few days

-------- Original Message --------

**Comment by inventortechie** [comment] 2017-11-13 20:26
I have no flickering issues. 7th Gen i7, HD 620.

**Comment by rolandguelle** [comment] 2017-11-13 20:39
I've no flickering issues with fresh 17.10 installation.

Do you tried the Razer Core setup, with bumblebee + primus-select?
I broke (5 minutes ago) my system with the Razer Core, bumblebee + primus-select and debugging the Webcam issue...
get now drm:...i915 error messages with broken Wayland & X :)

**Comment by rolandguelle** [comment] 2017-11-13 21:17
Fixed _my_ problem, with a misplaced /etc/ld.conf.d file.
@ahmadnassri do you installed / updated something special or disabled some software repos?

**Comment by ahmadnassri** [comment] 2017-11-14 04:20
@rolandguelle I don't have the Razer Core, does it make sense to try the setup despite lacking the hardware? not seeing what I would benefit, unless I'm missing something

**Comment by ahmadnassri** [comment] 2017-11-14 04:23
also, thank you all for responding here :)

**Comment by rolandguelle** [comment] 2017-11-14 05:28
@ahmadnassri If you don't use the Razer Core, ignore my comment.
I've never seen the flickering problem - not with 16.10,17.04, 17.10.
But I read about it:
https://wiki.archlinux.org/index.php/Razer_Blade#Graphics_Drivers

Check your logs / dmsg, if you got something like:
`[drm:intel_cpu_fifo_underrun_irq_handler [i915]] *ERROR* CPU pipe A FIFO underrun`
you should try:
* i915.enable_rc6=0
with the kernel or change the Xorg config with `Option "TearFree" "true"`.

I close this issue here, seems that the problem has something todo with your hardware.
If this helps, feedback would be great and I add this to this tutorial.

**Comment by uF4No** [comment] 2017-11-14 12:04
@ahmadnassri I have the flickering issue with my blade stealth (8th Gen i7). I've noticed it doesnt happen while I'm touching the trackpad (which is kinda weird....)
I'll check the logs @rolandguelle mentioned. By the way, thanks for all the info you've collected here mate!

**Comment by ahmadnassri** [comment] 2017-11-21 23:43
I've done a fresh install, and the issue went away, guessing too much fiddling with config settings!

@uF4No you're welcome :+1:

**Comment by brendanrankin** [comment] 2018-02-15 08:14
Flickering is fixed finally (for me) with i915.edp_vswing=2 setting. I didn't look closely at what it does (something to do with LED backlighting), but it was the only thing that worked for me on a late 2017 (i8550u) rbs.

Posting this here for posterity's sake. Cheers!

**Comment by rolandguelle** [comment] 2018-02-18 15:07
Thanks for repoting this fix @brendanrankin . I'll add this fix.

**Comment by rolandguelle** [comment] 2018-02-18 16:06
done. see also:
https://wiki.archlinux.org/index.php/Razer_Blade#Late-2017_version_Razer_Blade_Stealth

**Comment by brendanrankin** [comment] 2018-05-07 01:33
It's a temporal fix @f37, unfortunately. As soon as you update to the 4.16 kernel series, it will break.

I'm not sure what the answer is at this point except to state that the i915 kernel guys obviously don't have a handle on this sort of problem and, IMHO, it's likely to be a long road to a "real" solution. My gut feeling says it's power savings methodology over functionality causing at least a portion of these sorts of problems (and a lack of modern laptop hardware to test on....perhaps...).

C'est la vie!

**Comment by BBBob** [comment] 2018-05-07 01:48
@brendanrankin  I also met this problem, and when I downgrade my kernel to 4.15.15, the problem was missing, see [this](https://bbs.archlinux.org/viewtopic.php?id=236493). But I see the page that *loqs* posted.

**Comment by brendanrankin** [comment] 2018-05-07 02:27
@BBBob, I know that downgrading to 4.15.x solves the issue, but that's not a good solution for me as 4.16 (and Fedora 28) have much better support for Thunderbolt...which I don't want to give up.

As far as the [link](https://01.org/linuxgraphics/documentation/how-report-bugs) that loqs provides, it contains instructions on how to report a bug to Intel's 01.org and/or freedesktop.org for i915. You can likely find something similar on freedesktop.org

My belief is that the problem is with the new kernel and/or in the i915 drm driver. For me, it happens with or without X/Xwayland, so it's not likely to be a "graphic overload" issue and it not "X/Wayland" related either. My bet is on something relating to the panel, itself, and how the driver manages (or fails to manage) the power or back lighting.

Someone needs to work a bug through 01.org/freedesktop.org. I don't have the time at the moment and won't until the end of May (or so).

**Comment by BBBob** [comment] 2018-05-07 03:47
@brendanrankin I think so. I am using archlinux, and it happens without X for me.

**Comment by brendanrankin** [comment] 2018-05-08 15:55
For >= 4.16 kernels and the return of "the dreaded flicker", I found that setting intel_idle.max_cstate=4 in the kernel boot parameters gives me a flicker free experience...so far.

Please refer to https://bugzilla.redhat.com/show_bug.cgi?id=1573482 and the link to a freedesktop bug contained therein for more information.

It seems that some experimentation of "best max_cstate" to use might be needed and, frankly, it should work regardless of c_state. Knowing that it doesn't points to the i915 guys using some sort of hardware resource that changes with c_state to calculate something (hunch).

As always, YMMV...

**Comment by rolandguelle** [comment] 2018-05-09 02:46
I reopen this issue, maybe combination of #18

**Comment by f37** [comment] 2018-05-09 16:13
thanks a lot guys. i'm very happy that i'm not alone with the problem and finally found the board to discuss the issue. Thanks @rolandguelle to add the workaround fix. You are doing a great job.
Thank you, community. :heart:

**Comment by rolandguelle** [comment] 2018-05-16 15:04
Thanks @f37 for your feedback. Which workaround fixes this issue?
Can we close this issue?

**Comment by f37** [comment] 2018-05-23 15:11
i915.edp_vswing=2 solved the screen flickering for me. But like @brendanrankin mentioned this is just a workaround, and a guess its a long way to go for the i915 community.

In my opinion the issue can be closed due to the fact that its less a razer system problem then a hardware unit messup. I'm unaware of your razer policy of problem responsibility.

**Comment by BBBob** [comment] 2018-05-28 16:54
@brendanrankin I updated my kernel to 4.16.11 today and I haven't seen the screen flickering till now without the "best max_cstate" parameter.

**Comment by BBBob** [comment] 2018-05-28 17:18
@brendanrankin  I am so sorry that I met the screen flickering again..... What a pity!

**Comment by f37** [comment] 2018-05-29 10:32
@BBBob I feel with you brother

**Comment by dummydata** [comment] 2018-06-16 23:02
I can confirm that the parameter: intel_idle.max_cstate=4 solved screen flicker issues for me on an early-2018 Razer Blade Stealth w/ kernel 4.16.13

**Closed** 2018-06-17 04:54 UTC

**Comment by mkhpalm** [comment] 2018-07-29 19:07
i7-8550U RBS here

I'm not sure if I'm the only one who knows this so I thought I'd share. I'm using a 4.17.8 kernel and as long as I'm not trying to run 3200x1800 resolution I do not get flickering omitting any 915 kernel boot perams. I run 2048x1152 with no HiDPI scaling and everything works great. I've tested with all the other 16:9 resolutions and it only starts flickering when I'm at 3200x1800. Might be a workaround for some people.

Probably the wrong place to say this but here is an additional note on the touchpads for this model. There is a device matching bug in the resolution and fuzz overrides under systemd's hwdb.

If you are using libinput and the cursor wobbles violently on the y axis you probably have this problem:
https://mikepalmer.net/razer-blade-stealth-libinput-touchpad-issues/

I've submitted a PR to fix it here:
https://github.com/systemd/systemd/pull/9746

**Comment by drusepth** [comment] 2018-08-31 06:35
Just to pipe in: I have an early-2018 RBS that was experiencing frequent flickering on a fresh 18.04.01 install. Setting the screen resolution to anything other than 3200x1800 seems to have "fixed the issue. 

Would love to try the real `intel_idle.max_cstate=4` solution, although I'm not sure where kernel parameters go. :+1:

**Comment by Cethy** [comment] 2018-11-29 19:37
IMHO, the trackpad twitching fix from @mkhpalm should be documented in the "Razer Blade Stealth 2018".
Just got one, with a fresh ubuntu 18.10 install, I had the problem.
To be honest, it's not perfect (the cursor feels like it's in 10fps), but the twitching is gone.

**Comment by Treagle350** [comment] 2019-01-08 01:06
I recently ran Ubuntu 18.04 from a live USB stick, and experienced a heavy amount of screen flickering.
**Updating the BIOS** (using windows) solved the problem entirely for me.

The BIOS updater can be found by searching your device on : 
https://support.razer.com/
And then selecting _Software and drivers_

I also found a manual provided by Razer that explains how to update your BIOS : 
https://dl.razer.com/drivers/BladeC1/Razer%20Blade%2015%20%282018%29%20BIOS%20update%20v1.05.pdf

Please make sure to install the _correct version_ of the BIOS updater.
Razer also recommends _updating windows_ to the latest version before attempting to update the BIOS.
Also make sure that your device _doesn't lose power_ during the update.

For people that are already running Linux, one workaround I can think of is to create a small partition on your hard drive, installing windows on it and then doing the update. After the BIOS update, you can delete the partition with windows on it and the problem should be fixed.

**Comment by rikhuijzer** [comment] 2021-02-09 10:01
For people being directed to this thread with screen flickering problems: After trying many different kernel parameters for `intel_idle.max_cstate=4`, I eventually fixed it by replacing my HDMI cable... Credits to [AskUbuntu](https://askubuntu.com/questions/1059769/ubuntu-18-04-external-full-hd-monitor-flicker).
